### ISSUE TITLE
Reproduce on RAP dataset

### ISSUE THREAD

**Issue by jiajunzhang16** [chufengt/iccv19_attribute#13]
hi, thanks for open source.

I tried to reproduce the results on RAP datasets.

There is quite a gap between paper and my reproduction. 

Paper : 
![Screenshot from 2020-05-25 14-07-16](https://user-images.githubusercontent.com/41944075/82783710-95dda980-9e91-11ea-82fb-601b2ba27314.png)

My reproduction: 
Last epoch:
![Screenshot from 2020-05-25 14-15-12](https://user-images.githubusercontent.com/41944075/82784057-59f71400-9e92-11ea-8bff-772275da457d.png) 

The 10th epoch: 
![Screenshot from 2020-05-25 14-22-40](https://user-images.githubusercontent.com/41944075/82784504-3c767a00-9e93-11ea-9f05-e9152fe294bf.png)

I found the 10th epoch is much closer to the paper results.  
How do you chose your best result ? (The best mA epoch or Recall epoch ?）

**Comment by KaiiZhang** [comment]
HI, i also want to reproduce on RAP dataset, I am troubled by a problem:
I use the way in [pedestrian-attribute-recognition-pytorch](https://github.com/dangweili/pedestrian-attribute-recognition-pytorch) to process Rap dataset.
I got two files: rap_partition.pkl and rap_partition.pkl
These two files cannot be directly applied to this project because of different formats.
How can I turn them into usable？
Can I have some suggestions? Thank you very much

**Comment by chufengt** [comment]
> HI, i also want to reproduce on RAP dataset, I am troubled by a problem:
> I use the way in [pedestrian-attribute-recognition-pytorch](https://github.com/dangweili/pedestrian-attribute-recognition-pytorch) to process Rap dataset.
> I got two files: rap_partition.pkl and rap_partition.pkl
> These two files cannot be directly applied to this project because of different formats.
> How can I turn them into usable？
> Can I have some suggestions? Thank you very much

refer to #4

**Comment by chufengt** [comment]
> hi, thanks for open source.
> 
> I tried to reproduce the results on RAP datasets.
> 
> There is quite a gap between paper and my reproduction.
> 
> Paper :
> ![Screenshot from 2020-05-25 14-07-16](https://user-images.githubusercontent.com/41944075/82783710-95dda980-9e91-11ea-82fb-601b2ba27314.png)
> 
> My reproduction:
> Last epoch:
> ![Screenshot from 2020-05-25 14-15-12](https://user-images.githubusercontent.com/41944075/82784057-59f71400-9e92-11ea-8bff-772275da457d.png)
> 
> The 10th epoch:
> ![Screenshot from 2020-05-25 14-22-40](https://user-images.githubusercontent.com/41944075/82784504-3c767a00-9e93-11ea-9f05-e9152fe294bf.png)
> 
> I found the 10th epoch is much closer to the paper results.
> How do you chose your best result ? (The best mA epoch or Recall epoch ?）

Did you correctly use the dataset and code?
I achieve the results after about 30 epochs, refer to the Supplementary Material for more training detals.
