### ISSUE TITLE
About accuracy calculation in test function

### ISSUE THREAD

**Issue by happyprotean** [chufengt/iccv19_attribute#15]
Thanks for your code sharing, it helps me a lot!
One question about the accuracy calculation :
 in your code(main.py, line 295), `accu = accu + tp / (tp + fn + fp)`
I just wondering why tn is ignored and accu is not: `accu = accu + (tp + tn) / (tp + fn + fp + tn)`?
It would be appreciated if you could give me some hints.

**Comment by chufengt** [comment]
I used the definition in previous works, e.g. Pedestrian Attribute Recognition: A Survey (Eq. 2).

**Comment by happyprotean** [comment]
Thanks for your reply :)
