### ISSUE TITLE
Attribute-wise AP

### ISSUE THREAD

**Issue by MoonBunnyZZZ** [chufengt/iccv19_attribute#16]
Could you show the whole attribute-wise AP on peta ,pa-100K and rap dataset? 
I want to know the detail of sota model that you proposed.Thank you very much.@chufengt

**Comment by chufengt** [comment]
RAP dataset
====================================================================================================
	     Attr              	p_true/n_true	p_tol/n_tol	p_pred/n_pred	cur_mA
	# 0: Female            	2391\5602	2488\5802	2591\5699	0.96327
	# 1: AgeLess16         	  61\8192	  81\8236	 105\8212	0.87387
	# 2: Age17-30          	2917\3010	3586\4731	4638\3679	0.72484
	# 3: Age31-45          	4038\1993	4650\3667	5712\2605	0.70594
	# 4: BodyFat           	 716\5995	1246\7071	1792\6525	0.71123
	# 5: BodyNormal        	6048\ 256	6181\2136	7928\ 389	0.54917
	# 6: BodyThin          	 332\6776	 774\7543	1099\7218	0.66363
	# 7: Customer          	7860\ 327	7898\ 419	7952\ 365	0.88781
	# 8: Clerk             	 350\7849	 382\7935	 436\7881	0.95270
	# 9: BaldHead          	  23\8256	  36\8281	  48\8269	0.81793
	#10: LongHair          	1418\6445	1525\6792	1765\6552	0.93937
	#11: BlackHair         	7779\ 275	7851\ 466	7970\ 347	0.79048
	#12: Hat               	 122\8113	 160\8157	 166\8151	0.87855
	#13: Glasses           	 449\7418	 575\7742	 773\7544	0.86951
	#14: Muffler           	  38\8180	  80\8237	  95\8222	0.73404
	#15: Shirt             	1550\6036	1858\6459	1973\6344	0.88437
	#16: Sweater           	 545\6633	 982\7335	1247\7070	0.72964
	#17: Vest              	 417\7742	 483\7834	 509\7808	0.92581
	#18: TShirt            	1538\5187	1960\6357	2708\5609	0.80032
	#19: Cotton            	1126\6211	1368\6949	1864\6453	0.85845
	#20: Jacket            	2226\4657	2611\5706	3275\5042	0.83435
	#21: Suit-Up           	 150\8021	 205\8112	 241\8076	0.86024
	#22: Tight             	 143\7846	 277\8040	 337\7980	0.74606
	#23: ShortSleeve       	 122\8068	 170\8147	 201\8116	0.85398
	#24: LongTrousers      	4357\3016	4642\3675	5016\3301	0.87964
	#25: Skirt             	 442\7623	 534\7783	 602\7715	0.90358
	#26: ShortSkirt        	 175\7958	 252\8065	 282\8035	0.84059
	#27: Dress             	 221\7923	 277\8040	 338\7979	0.89164
	#28: Jeans             	2078\5613	2266\6051	2516\5801	0.92232
	#29: TightTrousers     	 990\6896	1088\7229	1323\6994	0.93193
	#30: LeatherShoes      	2153\5097	2459\5858	2914\5403	0.87283
	#31: SportShoes        	1972\4619	2308\6009	3362\4955	0.81155
	#32: Boots             	 933\7091	 997\7320	1162\7155	0.95226
	#33: ClothShoes        	  73\8148	 102\8215	 140\8177	0.85377
	#34: CasualShoes       	 731\5928	1341\6976	1779\6538	0.69744
	#35: Backpack          	  90\8097	 128\8189	 182\8135	0.84595
	#36: SSBag             	 389\7555	 569\7748	 582\7735	0.82937
	#37: HandBag           	 155\7944	 212\8105	 316\8001	0.85563
	#38: Box               	 220\7784	 349\7968	 404\7913	0.80364
	#39: PlasticBag        	 130\7971	 212\8105	 264\8053	0.79834
	#40: PaperBag          	  56\8135	 129\8188	 109\8208	0.71382
	#41: HandTrunk         	 169\8034	 215\8102	 237\8080	0.88883
	#42: OtherAttchment    	1792\4855	2442\5875	2812\5505	0.78010
	#43: Calling           	 226\7948	 276\8041	 319\7998	0.90364
	#44: Talking           	  67\7808	 270\8047	 306\8011	0.60922
	#45: Gathering         	 292\7002	 767\7550	 840\7477	0.65406
	#46: Holding           	  70\7959	 201\8116	 227\8090	0.66446
	#47: Pusing            	  71\8179	  90\8227	 119\8198	0.89153
	#48: Pulling           	  96\8077	 152\8165	 184\8133	0.81040
	#49: CarryingbyArm     	  69\8035	 179\8138	 172\8145	0.68641
	#50: CarryingbyHand    	 881\6774	1090\7227	1334\6983	0.87279
	mA:        0.8180646288320306
	Accuracy:  0.6756303140525949
	Precision: 0.7444815909560241
	Recall:    0.8662904719490501
	F1_Score:  0.8007803507884419
====================================================================================================

PETA dataset
====================================================================================================
	     Attr              	p_true/n_true	p_tol/n_tol	p_pred/n_pred	cur_mA
	# 0: Age16-30          	3404\3260	3728\3872	4016\3584	0.87752
	# 1: Age31-45          	2111\4389	2514\5086	2808\4792	0.85133
	# 2: Age46-60          	 584\6719	 790\6810	 675\6925	0.86294
	# 3: AgeAbove61        	 435\7099	 479\7121	 457\7143	0.95253
	# 4: Backpack          	1182\5699	1444\6156	1639\5961	0.87216
	# 5: CarryingOther     	 981\5741	1511\6089	1329\6271	0.79604
	# 6: Casual lower      	6431\ 805	6523\1077	6703\ 897	0.86667
	# 7: Casual upper      	6341\ 857	6468\1132	6616\ 984	0.86872
	# 8: Formal lower      	 858\6354	1062\6538	1042\6558	0.88988
	# 9: Formal upper      	 853\6354	1042\6558	1057\6543	0.89376
	#10: Hat               	 672\6761	 772\6828	 739\6861	0.93033
	#11: Jacket            	 320\6947	 515\7085	 458\7142	0.80094
	#12: Jeans             	1917\4925	2279\5321	2313\5287	0.88337
	#13: Leather Shoes     	2030\4888	2293\5307	2449\5151	0.90318
	#14: Logo              	 181\7152	 290\7310	 339\7261	0.80126
	#15: Long hair         	1694\5438	1827\5773	2029\5571	0.93459
	#16: Male              	3995\3099	4180\3420	4316\3284	0.93094
	#17: Messenger Bag     	1819\4809	2237\5363	2373\5227	0.85492
	#18: Muffler           	 586\6947	 637\6963	 602\6998	0.95882
	#19: No accessory      	5524\1470	5673\1927	5981\1619	0.86829
	#20: No carrying       	1741\4964	2140\5460	2237\5363	0.86135
	#21: Plaid             	 155\7336	 193\7407	 226\7374	0.89676
	#22: PlasticBags       	 443\6927	 574\7026	 542\7058	0.87884
	#23: Sandals           	  87\7336	 165\7435	 186\7414	0.75698
	#24: Shoes             	2091\4252	2763\4837	2676\4924	0.81792
	#25: Shorts            	 180\7266	 259\7341	 255\7345	0.84238
	#26: Short Sleeve      	 929\6213	1083\6517	1233\6367	0.90558
	#27: Skirt             	 247\7155	 337\7263	 355\7245	0.85903
	#28: Sneaker           	1188\5498	1600\6000	1690\5910	0.82942
	#29: Stripes           	  84\7405	 131\7469	 148\7452	0.81633
	#30: Sunglasses        	 117\7244	 224\7376	 249\7351	0.75221
	#31: Trousers          	3574\3057	3932\3668	4185\3415	0.87119
	#32: Tshirt            	 461\6691	 638\6962	 732\6868	0.84182
	#33: UpperOther        	2939\3705	3456\4144	3378\4222	0.87223
	#34: V-Neck            	  55\7439	  89\7511	 127\7473	0.80420
	mA:        0.8629834544966136
	Accuracy:  0.7952516984434543
	Precision: 0.8565327742432951
	Recall:    0.8808903081567429
	F1_Score:  0.8685408028622027
====================================================================================================

PA-100K dataset
====================================================================================================
	     Attr              	p_true/n_true	p_tol/n_tol	p_pred/n_pred	cur_mA
	# 0: Female            	3476\5457	3896\6104	4123\5877	0.89310
	# 1: AgeOver60         	 165\9500	 258\9742	 407\9593	0.80735
	# 2: Age18-60          	9556\ 152	9650\ 350	9754\ 246	0.71227
	# 3: AgeLess18         	  40\9817	  92\9908	 131\9869	0.71280
	# 4: Front             	2628\6351	2967\7033	3310\6690	0.89439
	# 5: Side              	3457\5206	3992\6008	4259\5741	0.86625
	# 6: Back              	2944\6182	3041\6959	3721\6279	0.92822
	# 7: Hat               	 101\9573	 287\9713	 241\9759	0.66875
	# 8: Glasses           	1982\6686	2464\7536	2832\7168	0.84580
	# 9: HandBag           	1029\7371	1465\8535	2193\7807	0.78300
	#10: ShoulderBag       	 958\7444	1955\8045	1559\8441	0.70766
	#11: Backpack          	1022\7969	1517\8483	1536\8464	0.80655
	#12: HoldObjectsInFront	  19\9839	 101\9899	  79\9921	0.59103
	#13: ShortSleeve       	3951\4996	4407\5593	4548\5452	0.89489
	#14: LongSleeve        	5278\3722	5593\4407	5963\4037	0.89412
	#15: UpperStride       	 527\9127	 635\9365	 765\9235	0.90225
	#16: UpperLogo         	 925\7755	1241\8759	1929\8071	0.81537
	#17: UpperPlaid        	 790\8136	1219\8781	1435\8565	0.78731
	#18: UpperSplice       	 344\9394	 447\9553	 503\9497	0.87647
	#19: LowerStripe       	  16\9909	  25\9975	  82\9918	0.81669
	#20: LowerPattern      	  71\9716	 119\9881	 236\9764	0.78997
	#21: LongCoat          	 315\9207	 448\9552	 660\9340	0.83350
	#22: Trousers          	7664\1652	7862\2138	8150\1850	0.87375
	#23: Shorts            	1070\8454	1286\8714	1330\8670	0.90110
	#24: Skirt&Dress       	 593\8732	 819\9181	1042\8958	0.83757
	#25: boots             	   1\9916	  55\9945	  30\9970	0.50763
	mA:        0.8056849179529115
	Accuracy:  0.751180085535366
	Precision: 0.8185561707736693
	Recall:    0.8813929365079477
	F1_Score:  0.84881320736549
====================================================================================================

**Comment by abhigoku10** [comment]
@how to obtain attribute wise mA?? what changes has to be made in the code

**Comment by chufengt** [comment]
The released code can print the attribute-wise mA.
See `test()` in main.py
