### ISSUE TITLE
关于属性定位可视化

### ISSUE THREAD

**Issue by TongYoungG** [chufengt/iccv19_attribute#17]
作者你好。

关于属性定位可视化，我看到您在之前的问题回答中提出，只需要获得 stn 的转换矩阵 theta_i，然后将变换矩阵直接应用到输入图像上即可。

是不是可以这样理解：
[1] stn 变换后的图像坐标归一化到 (-1,1)
[2] 可以根据 stn 变换后归一化的左上角坐标 (-1,-1) 和 右下角坐标 (1,1) 求得 stn 变换前对应在原图像中的对应坐标（也是归一化为(-1,-1)）
[3] 将 [2] 中求得的归一化坐标反归一化，得到的坐标即为属性定位的目标框。

但是我得到的目标框感觉不对，我是根据下图进行理解的，请指正一下，谢谢。
![1594283080(1)](https://user-images.githubusercontent.com/6924670/87016121-e0787280-c200-11ea-81b8-7d477746aaa2.jpg)

**Comment by chufengt** [comment]
可视化不一定要把theta转成bounding box的格式，只需要用theta去原图里把对应的区域抠出来就行了
比如用pytorch提供的F. affine_grid, F. grid_sample函数
参考 https://pytorch.org/tutorials/intermediate/spatial_transformer_tutorial.html

**Comment by TongYoungG** [comment]
谢谢您的回复，您提到的这种可视化我已经实现。

我主要想做出和论文中 “属性定位可视化” 的展示图一样的效果，请问这个是如何做出来的？是先把区域先抠出来再映射回原图吗？
![15943493383274177131308522791741](https://user-images.githubusercontent.com/6924670/87111028-ffc3de00-c29a-11ea-9a5d-cc5821454c36.jpg)

**Comment by chufengt** [comment]
你好，这个图并不是通过bounding box画出来的，而是我人为根据抠出来的sub-region去原图上框出来的，这只是个示意图，表明三个level的不同即可，不会很精确。

**Comment by TongYoungG** [comment]
原来如此，那我清楚了，非常感谢！
