### ISSUE TITLE
FLOPS Problem

### ISSUE THREAD

**Issue by gongliuqing123** [chufengt/iccv19_attribute#18]
你好、谢谢你的开源：
    请问一下、我在训练自己的数据集的时候，基本上是1.5个小时迭代一次、有60多个属性。使用训练好的权重预测图像的时候基本上也是0.6s一帧、在GPU服务器上、请问你也是这样的情况吗？

**Comment by chufengt** [comment]
具体的时间记不太清了，但是训练RAP这种小数据集10-15epochs大概就几个小时吧
