### ISSUE TITLE
Visualization of Attribute Localization

### ISSUE THREAD

**Issue by Youskrpig** [chufengt/iccv19_attribute#2]
Hey,  I wanna ask how can i realize the Visualization of attribute localization results at different
feature levels? It seems the visualization code is not included.

**Comment by chufengt** [comment]
The visualization codes are removed for brevity.
Actually, at each feature level, the model will give an affine transformation matrix (2*3) for each attribute (the variable 'theta' in our codes).
For visualization, you can directly apply this affine transformation matrix to the input image.
Ref.: https://pytorch.org/tutorials/intermediate/spatial_transformer_tutorial.html
