### ISSUE TITLE
FLOPs in paper 

### ISSUE THREAD

**Issue by jiajunzhang16** [chufengt/iccv19_attribute#22]
Hi, 
Thanks for your work. 

I wonder How do you calculate your GFLOPs in your paper? 

I tried some open-source work https://github.com/Lyken17/pytorch-OpCounter  and  https://github.com/sovrasov/flops-counter.pytorch   But the result is quite different from its in paper,  could you please share this part ?

**Comment by chufengt** [comment]
I used the THOP, example code:
```
import model as models
from thop import profile

model = models.__dict__['inception_iccv'](pretrained=False, num_classes=51)

flops, params = profile(model, input_size=(1, 3, 256, 128))
print(flops/1e9, params/1000/1000)
```

**Comment by jiajunzhang16** [comment]
> I used the THOP, example code:
> 
> ```
> import model as models
> from thop import profile
> 
> model = models.__dict__['inception_iccv'](pretrained=False, num_classes=51)
> 
> flops, params = profile(model, input_size=(1, 3, 256, 128))
> print(flops/1e9, params/1000/1000)
> ```

Thanks for reply,  I have tried your solution, but got the results:

> ```
> from model.inception_iccv import inception_iccv
> from thop import profile
> import torch
> with torch.cuda.device(2):
>     model = inception_iccv(pretrained=False,num_classes=51).cuda().eval()
>     input = torch.randn(1,3,256,128).cuda()
>     flops, params = profile(model, inputs=(input,))
>     print(flops/1e9, params/1000/1000)
> ```

![Screenshot from 2020-09-04 22-06-45](https://user-images.githubusercontent.com/41944075/92248447-49c3eb80-eefb-11ea-8573-e91162db62bc.png)

#p is fine, but GFLOPs still not right. 

I am new to THOP, any suggestion?

**Comment by chufengt** [comment]
The above codes are exactly the codes I used in my experiments, while I have never seen these warnings.
Maybe due to the version of PyTorch or THOP? I used PyTorch 0.4 when preparing the table.
