### ISSUE TITLE
How to load datasets ?

### ISSUE THREAD

**Issue by zhishao** [chufengt/iccv19_attribute#23]
```
train_dataset = MultiLabelDataset(root='data_path',
                    label='train_list_path', transform=transform_train)
val_dataset = MultiLabelDataset(root='data_path',
                    label='val_list_path', transform=transform_test)
```
pls give an eg for the 'data_path' and 'train_list_path' and 'val_list_path', thank you...

**Comment by chufengt** [comment]
Sorry for the late reply, please refer to #4 .

**Comment by eeric** [comment]
> ```
> train_dataset = MultiLabelDataset(root='data_path',
>                     label='train_list_path', transform=transform_train)
> val_dataset = MultiLabelDataset(root='data_path',
>                     label='val_list_path', transform=transform_test)
> ```
> 
> pls give an eg for the 'data_path' and 'train_list_path' and 'val_list_path', thank you...

https://github.com/chufengt/iccv19_attribute/issues/37

**Comment by eeric** [comment]
https://github.com/chufengt/iccv19_attribute/issues/37
