### ISSUE TITLE
Can you translate the label of pa100k dataset into Chinese pls

### ISSUE THREAD

**Issue by zhishao** [chufengt/iccv19_attribute#24]
I don't understand the meaning of the labels in chinese , especially “UpperStride” “UpperSplice” “LowerStripe” "LowerPattern".

**Comment by chufengt** [comment]
Sorry I was also not familiar with it. 
You can pick up some samples to distinguish these concepts.

**Comment by zhishao** [comment]
@chufengt  I've saw some samples but its just Some Pattern, the 4 labels are hard to see different ,so I think even model can not figer out , its obstacles to accuracy.
