### ISSUE TITLE
accu calculate

### ISSUE THREAD

**Issue by DRACOyu** [chufengt/iccv19_attribute#26]
accu = accu + 1.0 *tp /(tp+fn+fp)   where tn???

**Comment by chufengt** [comment]
similar to issue #15

**Comment by DRACOyu** [comment]
> similar to issue #15
remove the imbalance of samples?

**Comment by chufengt** [comment]
> > similar to issue #15
> > remove the imbalance of samples?

It seems a common practice in multi-label problems, actually, I just followed the previous papers/codebases.
(Ref. https://cs.nju.edu.cn/zhouzh/zhouzh.files/publication/tkde13rev.pdf)

**Comment by DRACOyu** [comment]
> > > similar to issue #15
> > > remove the imbalance of samples?
> 
> It seems a common practice in multi-label problems, actually, I just followed the previous papers/codebases.
> (Ref. https://cs.nju.edu.cn/zhouzh/zhouzh.files/publication/tkde13rev.pdf)

Thank you. What is your GPU type？v100 batch32？

**Comment by chufengt** [comment]
> > > > similar to issue #15
> > > > remove the imbalance of samples?
> > 
> > 
> > It seems a common practice in multi-label problems, actually, I just followed the previous papers/codebases.
> > (Ref. https://cs.nju.edu.cn/zhouzh/zhouzh.files/publication/tkde13rev.pdf)
> 
> Thank you. What is your GPU type？v100 batch32？

1080Ti
