### ISSUE TITLE
test trained model on random images

### ISSUE THREAD

**Issue by TinBarbie** [chufengt/iccv19_attribute#27]
Hi Mr.chufengt, are there any tutorials or codes about running test on random images i already downloaded in the internet? 
Thanks in advance.

**Comment by chufengt** [comment]
You can create a data list and put the images and list into the test_path (refer to utils/datasets.py).
After that, download the pre-trained models and perform inference.

**Comment by eeric** [comment]
> Hi Mr.chufengt, are there any tutorials or codes about running test on random images i already downloaded in the internet?
> Thanks in advance.

https://github.com/chufengt/iccv19_attribute/issues/37
