### ISSUE TITLE
Visualization Code 

### ISSUE THREAD

**Issue by zhangzhiyong176** [chufengt/iccv19_attribute#29]
Hi, Could the code of visualization of attribute localization results share?

**Comment by chufengt** [comment]
similar to issue #17, also see https://pytorch.org/tutorials/intermediate/spatial_transformer_tutorial.html

**Comment by zhangzhiyong176** [comment]
> similar to issue #17, also see https://pytorch.org/tutorials/intermediate/spatial_transformer_tutorial.html



> similar to issue #17, also see https://pytorch.org/tutorials/intermediate/spatial_transformer_tutorial.html

thanks

**Comment by abhigoku10** [comment]
@Aismarter  can you share the visualization code base it will helpful !!!
