### ISSUE TITLE
Result of mA is 0.81?

### ISSUE THREAD

**Issue by guanhuiyan** [chufengt/iccv19_attribute#3]
PETA
Why is there a big gap between my results and yours？

**Comment by chufengt** [comment]
For PETA dataset, some simple baselines can achieve mA larger than 81%.
Please check your dataset and codes, e.g. correct weighted loss, correct dataset, ...

**Comment by guanhuiyan** [comment]
谢谢，我再多尝试发自我的华为手机-------- 原始邮件 --------主题：Re: [chufengt/iccv19_attribute] Result of mA is 0.81? (#3)发件人：Chufeng Tang 收件人：chufengt/iccv19_attribute 抄送：guanhuiyan ,Author For PETA dataset, some simple baselines can achieve mA larger than 81%.
Please check your dataset and codes, e.g. correct weighted loss, correct dataset, ...

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/chufengt/iccv19_attribute/issues/3?email_source=notifications\u0026email_token=AJOY63GW5EGFD2L66BIA5MDRGITTPA5CNFSM4LCX7CLKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEODWS7Y#issuecomment-596076927",
"url": "https://github.com/chufengt/iccv19_attribute/issues/3?email_source=notifications\u0026email_token=AJOY63GW5EGFD2L66BIA5MDRGITTPA5CNFSM4LCX7CLKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEODWS7Y#issuecomment-596076927",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
