### ISSUE TITLE
Hello,what's the data performance of body-parts guided module compare with attention module

### ISSUE THREAD

**Issue by Ronales** [chufengt/iccv19_attribute#30]
Dear author:

     I have a problem that how the performance of the body-part guided module in your paper appendix. I just watch some results visualization at the end, whether this module has better performance compared with the attention module?

    thanks!

**Comment by chufengt** [comment]
Please see Table 2 in the main paper.

**Comment by Ronales** [comment]
Ok, I get it! Maybe the attention method can give better performance compared with the simple region choice?

**Comment by chufengt** [comment]
You mean "attention mask" in Table 2? 
The attention mask gives more flexibility than rigid body-parts, while the ideal attention map is hard to learn with only attribute annotation.
See section 4.4 in our paper for details.

**Comment by Ronales** [comment]
Thanks for your reply！
