### ISSUE TITLE
problems on visualization

### ISSUE THREAD

**Issue by rexyang94** [chufengt/iccv19_attribute#31]
论文中的theta格式是[[x1,0,x2],[0,x3,x4]]，也就是说仅对图像进行缩放和平移。
对于可视化，我的理解提取出各个layerd的theta后，直接在原图进行stn变换得到的注意力区域。
仅对图像进行缩放和平移，得到必然是一个边缘的区域，不会是图像中间的某一块图像，请问是怎样实现figure 5 （a）这样的可视化结果是怎么来，感觉是不可能变换出中间这样的区域的，我的理解可能出现了一点错误，希望能够得到解答

![图片1](https://user-images.githubusercontent.com/30064126/114665829-13233e80-9d30-11eb-9c02-5c3811f876db.png)

**Comment by chufengt** [comment]
平移自然包括横向和纵向，因此可以出现在图像中心。

https://pytorch.org/tutorials/intermediate/spatial_transformer_tutorial.html
可以参考这个tutorial，设一些theta的值然后可视化出来看看。

**Comment by rexyang94** [comment]
我就是按着这个tutorial进行测试的，可视化出来的都是边缘的结果。多次横向、纵向平移是可以获得中心区域，但是仅进行一次变换，感觉是不能得到中心区域

**Comment by chufengt** [comment]
> we simply constrain sx,sy to (0, 1) and tx, ty to (−1, 1) by a sigmoid and tanh activation

你试试这个范围内的theta吧

或者你看官方这个MNIST的例子，有些没有旋转的case，其实也是中心区域附近的

**Comment by rexyang94** [comment]
没有想到放大可以改变边缘结果，谢谢大佬的耐心解答，万分感谢！

**Comment by abhigoku10** [comment]
@rexyang94  can you let us knw how to visualize the bounding boxes of the results , can you share the code @chufengt i checked ur suggestion of seeing the mnist data i get error "AttributeError: 'DataParallel' object has no attribute 'stn'"
