### ISSUE TITLE
TensorRT model conversion 

### ISSUE THREAD

**Issue by abhigoku10** [chufengt/iccv19_attribute#34]
@chufengt  can we convert the current pretrained or custom model into tensor rt for faster inference ?

**Comment by chufengt** [comment]
Sorry, I have no experience with Tensor RT. You can have a try.

**Comment by A7med01** [comment]
@abhigoku10 did you successfully convert the model to tensor rt??

**Comment by abhigoku10** [comment]
@chufengt  nope i did not go to that phase of conversion , do let me knw if your able to convert

**Comment by abhigoku10** [comment]
@chufengt @A7med01  i am getting this below error when converting to onnx "RuntimeError: Exporting the operator affine_grid_generator to ONNX opset version 11 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub"

**Comment by abhigoku10** [comment]
solved in #44
