### ISSUE TITLE
Training Details 

### ISSUE THREAD

**Issue by abhigoku10** [chufengt/iccv19_attribute#35]
@chufengt  Can you please share more insights on the training details performed like final loss 
1.To see moderate good predictions how much custom data for the attributes should be given for training 
2.If we annotate the RAP/PETA/PA data for male class and train the model will there be drop in accuracy of the model i.e FP or misclassification can increase 

Thanks in advance

**Comment by chufengt** [comment]
1. It's hard to say. You can refer to the number of images in RAP etc.
2. You mean only train the male class? I think the accuracy may not decrease since this class is a really easy one.
