### ISSUE TITLE
属性定位问题

### ISSUE THREAD

**Issue by eeric** [chufengt/iccv19_attribute#39]
文章提到属性定位模块（ALM），以弱监督的方式自动发现每个属性的判别力区域。
请问，仅靠ALM能较准确的把标签与对应图像patch对应起来吗？
比如，帽子标签，能通过ALM，与头部图像区域对应起来吗

**Comment by chufengt** [comment]
由于是弱监督，所以也谈不上非常“准确”，但是我自己看的一些可视化结果是对应得不错的。

**Comment by eeric** [comment]
在utils/datasets.py里面的peta数据标签的排列，并不是按从头到脚的顺序，
如果增加标签，直接使用本项目训练，也能对应起来吧

**Comment by chufengt** [comment]
与排列无关，能否对应起来取决于模型是否倾向基于该局部区域的特征进行分类
模型并没有明确的监督信号来学习该对应关系

**Comment by eeric** [comment]
哦，那就是关键在于网络模型设计了。
如果属性重叠，那么识别效果可能会差一点。
peta数据库
较好的属性：
#3: AgeAbove61          427\7100        479\7121        448\7152       0.94425
#10: Hat                 628\6764        772\6828        692\6908       0.90205
#15: Long hair          1538\5447       1827\5773       1864\5736       0.89267
#16: Male               3967\2891       4180\3420       4496\3104       0.89718
#18: Muffler             571\6936        637\6963        598\7002       0.94626
较差的属性
#14: Logo                107\7038        290\7310        379\7221       0.66588
#23: Sandals              59\7338        165\7435        156\7444       0.67226
#29: Stripes              36\7395        131\7469        110\7490       0.63245
#30: Sunglasses           81\7180        224\7376        277\7323       0.66752

**Comment by nanhui69** [comment]
> 哦，那就是关键在于网络模型设计了。
> 如果属性重叠，那么识别效果可能会差一点。
> peta数据库
> 较好的属性：
> #3: AgeAbove61 427\7100 479\7121 448\7152 0.94425
> #10: Hat 628\6764 772\6828 692\6908 0.90205
> #15: Long hair 1538\5447 1827\5773 1864\5736 0.89267
> #16: Male 3967\2891 4180\3420 4496\3104 0.89718
> #18: Muffler 571\6936 637\6963 598\7002 0.94626
> 较差的属性
> #14: Logo 107\7038 290\7310 379\7221 0.66588
> #23: Sandals 59\7338 165\7435 156\7444 0.67226
> #29: Stripes 36\7395 131\7469 110\7490 0.63245
> #30: Sunglasses 81\7180 224\7376 277\7323 0.66752

hei ,do you get good performance in this original model?

**Comment by eeric** [comment]
比作者的准确率低1%左右，具体没有调参。
