### ISSUE TITLE
rap数据库属性共有92个

### ISSUE THREAD

**Issue by eeric** [chufengt/iccv19_attribute#40]
作者您好
如果采用92个属性，那么Weighted_BCELoss如何计算呢？

**Comment by chufengt** [comment]
统计多出这部分属性的正负样本比例，用文中的公式计算一下weights即可。

**Comment by eeric** [comment]
Multi-attribute learning for pedestrian attribute recognition in surveillance scenarios
是公式6吧？

**Comment by eeric** [comment]
@chufengt 
晚上好！
在main.py中，rap数据库的Weighted_BCELoss值，应该是pos的比率，即pl，而不是exp(1-pl)，是吗？

**Comment by chufengt** [comment]
您好我刚看到 目前手边没有电脑 不过应该是您后面说这种 联系参考我本人论文中的公式

**Comment by eeric** [comment]
> 您好我刚看到 目前手边没有电脑 不过应该是您后面说这种 联系参考我本人论文中的公式
恩，你抽空确认下是哪篇文献，具体在哪？
另外，Weighted_BCELoss值，应该是pos的比率，即pl，对吗？
先谢谢了。

**Comment by chufengt** [comment]
在论文公式(5)下方的文字中

**Comment by eeric** [comment]
找到了。
am is the prior class distribution of m-th attribute
am就是正类数量占训练集数量的比率吗？

**Comment by chufengt** [comment]
是的

**Comment by eeric** [comment]
好，多谢！
