### ISSUE TITLE
训练过拟合

### ISSUE THREAD

**Issue by eeric** [chufengt/iccv19_attribute#41]
@chufengt 
晚上好！   
请问你有没有遇到该项目训练时在前20轮就会出现过拟合的情况，你认为该如何避免？

**Comment by chufengt** [comment]
数据集普遍比较小，比如RAP和PETA，过拟合应该也比较正常，尝试调整一下超参数吧，或者不需要训练那么长时间。

**Comment by eeric** [comment]
ok, thanks a lot!
