### ISSUE TITLE
Custom backbone instead of Inception

### ISSUE THREAD

**Issue by sudapure** [chufengt/iccv19_attribute#42]
From the code-base and paper implementation it looks like inception backbone is very native and adaptive to the complete attribute specified localization network, however the `BNInceptionNet` is bit heavy and contribute to high number of latency time during inference which makes it practically not suitable for the real-time surveillance scenarios, so will it be possible to replace the inception backbone network with any other lightweight backbones like mobilenet ,effecientNet-l0, etc, if it is feasible then how much it could impact the speed/accuracy factor.

**Comment by chufengt** [comment]
Sure. It's ok to replace the backbone network. 
The only modification is to choose a proper location to append the ALM modules.
Speed can be improved with lightweight backbones.

**Comment by nanhui69** [comment]
> Sure. It's ok to replace the backbone network.
> The only modification is to choose a proper location to append the ALM modules.
> Speed can be improved with lightweight backbones.

in such case ? where can we use it for replace the model backbone..?

**Comment by chufengt** [comment]
> > Sure. It's ok to replace the backbone network.
> > The only modification is to choose a proper location to append the ALM modules.
> > Speed can be improved with lightweight backbones.
> 
> in such case ? where can we use it for replace the model backbone..?

`BNInception` class in `inception_iccv.py` defined the backbone.
You can replace it with others, like ResNet, and modify the corresponding codes in  the `InceptionNet` class.
