### ISSUE TITLE
the ALM modules

### ISSUE THREAD

**Issue by eeric** [chufengt/iccv19_attribute#43]
@chufengt 
the ALM modules could weakly supervised special attribute learning, through ALM,  special attribute corresponding to body-part.
was there any way to improve ALM?

**Comment by chufengt** [comment]
You can see some newly published works in this area.

**Comment by eeric** [comment]
ok, for spatial transformer improvement, what about your advice?

**Comment by chufengt** [comment]
there are some follow-up works behind STN, you can see these works

**Comment by eeric** [comment]
could you recommend  follow-up works behind STN?

**Comment by chufengt** [comment]
like this one:
Inverse compositional spatial transformer networks, 2016.

**Comment by eeric** [comment]
good advice, thanks.
