### ISSUE TITLE
error that convert model from pytorch to onnx

### ISSUE THREAD

**Issue by eeric** [chufengt/iccv19_attribute#44]
hi, could you convert model from pytorch to onnx?
error:
1. theta_i = self.stn_list[i](F.avg_pool2d(stn_feature, stn_feature.size()[2:]).view(bs,-1)).view(-1,4), ##the reason RuntimeError: Failed to export an ONNX attribute 'onnx::Gather', since it's not constant,

2.RuntimeError: Exporting the operator affine_grid_generator to ONNX opset version 11 is not supported. Please open a bug to request ONNX export support for the missing operator.

**Comment by eeric** [comment]
or is there an alternative to replace spatial transformer means?

**Comment by chufengt** [comment]
1. Sorry, I have no experience with ONNX.
2. I didn't try to replace the STN. Actually, the STN module in our model can be viewed as roi pooling with learnable boxes. You can try to re-implement it in an ONNX-compatible manner.

**Comment by eeric** [comment]
removing F.affine_grid与F.grid_sample,
in my experiment, ap decreased by 0.3%.

**Comment by chufengt** [comment]
You mean removing the ALM module?

**Comment by eeric** [comment]
only remove line 81,82,84 in model/inception_iccv.py.

**Comment by A7med01** [comment]
@eeric  could you share the code you used to convert model from pytorch to onnx ?

**Comment by eeric** [comment]
@A7med01 
this work is easy, you can look up torch.onnx.
in addition, you need to process model format to torch.nn.DataParallel.

**Comment by A7med01** [comment]
@eeric 
this is my code , what is wrong ?
```

import torch
import torch.onnx
attr_num = 6
model_agg = models.__dict__["inception_iccv"](pretrained=True, num_classes=attr_num)
model_agg = torch.nn.DataParallel(model_agg).cuda()
    
checkpoint = torch.load("61.pth.tar")
model_agg.load_state_dict(checkpoint['state_dict'])

# Create the right input shape (e.g. for an image)
dummy_input = torch.randn(1, 3, 224, 224)
torch.onnx.export(model_agg.module, dummy_input, "onnx_model_name.onnx")

```

**Comment by A7med01** [comment]
@eeric
this is my code , what is wrong ? 
```

import torch
import torch.onnx
attr_num = 6
model_agg = models.__dict__["inception_iccv"](pretrained=True, num_classes=attr_num)
model_agg = torch.nn.DataParallel(model_agg).cuda()
    
checkpoint = torch.load("61.pth.tar")
model_agg.load_state_dict(checkpoint['state_dict'])

# Create the right input shape (e.g. for an image)
dummy_input = torch.randn(1, 3, 256, 128)
torch.onnx.export(model_agg.module, dummy_input, "onnx_model_name.onnx")
```

**Comment by eeric** [comment]
loading model param as following:
https://blog.csdn.net/wuqingshan2010/article/details/111386066

others is good

**Comment by A7med01** [comment]
@eeric 
do you mean to add the **device** part 

```
import torch
import torch.onnx


attr_num = 6
model_agg = models.__dict__["inception_iccv"](pretrained=True, num_classes=attr_num)

device = torch.device("cuda")
model_agg = model_agg.to(device)

model_agg = torch.nn.DataParallel(model_agg).cuda()

checkpoint = torch.load("61.pth.tar")
model_agg.load_state_dict(checkpoint['state_dict'])

dummy_input = torch.randn(1, 3, 256, 128)
torch.onnx.export(model_agg.module, dummy_input, "onnx_model_name.onnx")
```
gives me this error :
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same

**Comment by A7med01** [comment]
@eeric 

please see if this is right :

```
import torch
import torch.onnx
from collections import OrderedDict
import model as models


device = torch.device("cuda")

attr_num = 6
model_agg = models.__dict__["inception_iccv"](pretrained=True, num_classes=attr_num)


model_agg = model_agg.to(device)

checkpoint = torch.load("61.pth.tar")

new_state_dict = OrderedDict()
for k, v in checkpoint.items():
    name = k[7:]  # remove "module."
    new_state_dict[name] = v


model_agg.load_state_dict(new_state_dict)
dummy_input = torch.randn(1, 3, 256, 128)
torch.onnx.export(net, dummy_input, "onnx_model_name.onnx")
```
it gives me error with `model_agg.load_state_dict(new_state_dict)` : 	Unexpected key(s) in state_dict: "", "ict", "cu".

**Comment by eeric** [comment]
change:
for k, v in checkpoint['state_dict'].items():

add:
dummy_input.to(device)

**Comment by A7med01** [comment]
@eeric  thank you , i changed it but still have error 




```
import torch
import torch.onnx
from collections import OrderedDict
import model as models


device = torch.device("cuda")

attr_num = 6
model_agg = models.__dict__["inception_iccv"](pretrained=True, num_classes=attr_num)


model_agg = model_agg.to(device)

checkpoint = torch.load("61.pth.tar")

new_state_dict = OrderedDict()
for k, v in checkpoint['state_dict'].items():
    name = k[7:]  # remove "module."
    new_state_dict[name] = v


model_agg.load_state_dict(new_state_dict)

dummy_input = torch.randn(1, 3, 256, 128)
dummy_input.to(device)


torch.onnx.export(model_agg, dummy_input, "onnx_model_name.onnx")
```

for line `torch.onnx.export(model_agg, dummy_input, "onnx_model_name.onnx")`

RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same

**Comment by A7med01** [comment]
@eeric I edited my code and now I have this error 


```
import torch
import torch.onnx
from collections import OrderedDict
import model as models

attr_num = 6
# create model
model_agg = models.__dict__["inception_iccv"](pretrained=True, num_classes=attr_num)

device = torch.device("cuda")



#model_agg = torch.nn.DataParallel(model_agg).cuda()

# load model 
#print("Model loading")

model_agg = model_agg.to(device)

    
checkpoint = torch.load("1_test.pth.tar")

new_state_dict = OrderedDict()
for k, v in checkpoint['state_dict'].items():
    name = k[7:]  # remove "module."
    new_state_dict[name] = v
    
    
model_agg.load_state_dict(new_state_dict)

# Create the right input shape (e.g. for an image)
# dummy_input = torch.randn(sample_batch_size, channel, height, width)
model_agg = model_agg.to(device)

dummy_input = torch.randn(1, 3, 256, 128)
dummy_input = dummy_input.to(device)

#torch.onnx.export(model_agg, dummy_input, "onnx_model_name.onnx")


torch.onnx.export(model_agg,               # model being run
                  dummy_input,                         # model input (or a tuple for multiple inputs)
                  "age_gender.onnx",   # where to save the model (can be a file or file-like object)
                  export_params=True,        # store the trained parameter weights inside the model file
                  opset_version=11,          # the ONNX version to export the model to
                  do_constant_folding=True,  # whether to execute constant folding for optimization
                  input_names = ['input'],   # the model's input names
                  output_names = ['output'], # the model's output names
                  dynamic_axes={'input' : {0 : 'batch_size'},    # variable length axes
                                'output' : {0 : 'batch_size'}})
```

RuntimeError: Failed to export an ONNX attribute 'onnx::Gather', since it's not constant, please try to make things (e.g., kernel size) static if possible

**Comment by A7med01** [comment]
> only remove line 81,82,84 in model/inception_iccv.py.

when you do this, do you successfully able to convert the model to onnx ?

**Comment by eeric** [comment]
onnx demo was ok, but error was 'onnx::Gather', I guess as below
only remove line 81,82,84 in model/inception_iccv.py.

**Comment by A7med01** [comment]
> onnx demo was ok, but error was 'onnx::Gather', I guess as below
> only remove line 81,82,84 in model/inception_iccv.py.

i removed these lines and still get same error

**Comment by eeric** [comment]
your model some op were not supported.
according to "since it's not constant", maybe convolution kernel size is not constant, eg: pooling.

**Comment by A7med01** [comment]
I replaced `x = F.avg_pool2d(x, x.size()[2:])` with :

```
x_shape = [int(s) for s in x.size()[2:]]
        
        x = F.avg_pool2d(x, x_shape)
```

the onnx model is now exported with removing lines 81,82,84 .
 how this affect model accuracy with you ? is there any alternatives to replace these lines ?

**Comment by eeric** [comment]
of course, when using author code.

**Comment by eeric** [comment]
> x.size()[2:]
haha, I caught the mistake, it's not constant.

**Comment by abhigoku10** [comment]
@A7med01 thanks for source code @eeric  @chufengt  did guys see what is the percentage drop in the accuracy ?? since it is mentioned 0.3% but when i tested it with RAP dataset below are the figures 

Pretrained model results on val set 
mA	0.8186197856
Accuracy	0.6735390288
Precision	0.7422611513
Recall	0.865414491
F1_Score	0.7991208419

After onnx and tensort conversion 
mA:        0.6860989716846921
mAP:       0.44124889829789654
Accuracy:  0.46312714193120047
Precision: 0.5046668156554033
Recall:    0.840410588870056
F1_Score:  0.6306363251678662

I have followed the same steps mentioned above any thoughts on this much difference

**Comment by A7med01** [comment]
@abhigoku10 can you share your code for ONNX evaluation to see if i get same numbers

**Comment by Y-T-G** [comment]
torch.onnx.errors.SymbolicValueError: Expected node type 'onnx::Constant' for argument 'kernel_size' of node 'symbolic_fn', got 'onnx::Loop'.  [Caused by the value '2061 defined in (%2061 : Long(device=cpu)[] = onnx::Loop(%2060, %1727, %size_array.2) # /home/ubuntu/yasin/PAR/ALM-pedestrian-attribute/model/inception_iccv.py:28:17

**Comment by Y-T-G** [comment]
I updated the model code without deleting any operations, so the accuracy is preserved. You can export it using ONNX with opset 16.

https://github.com/Y-T-G/ALM-pedestrian-attribute/blob/master/model/inception_iccv.py

**Comment by Y-T-G** [comment]
I removed SpatialTransformBlock completely by editing the forward function:
https://github.com/chufengt/ALM-pedestrian-attribute/blob/8462c298121d2be8a6e9e3d8affc5bd2561d21a1/model/inception_iccv.py#L135

to:

```python
    def forward(self, input):
        bs = input.size(0)
        feat_3b, feat_4d, feat_5b = self.main_branch(input)
        main_feat = self.global_pool(feat_5b).view(bs,-1)
        main_pred = self.finalfc(main_feat)

        fusion_5b = self.latlayer_5b(feat_5b)
        fusion_4d = self._upsample_add(fusion_5b, self.latlayer_4d(feat_4d))
        fusion_3b = self._upsample_add(fusion_4d, self.latlayer_3b(feat_3b))

        return main_pred
```

My accuracy dropped very little. Less than 0.1%.
