### ISSUE TITLE
Calculate positive labels for each attribute

### ISSUE THREAD

**Issue by phuonganhdo1808** [chufengt/iccv19_attribute#45]
Hi @chufengt , can I have some advice to calculate the ratio of positive labels when I have train on my custom dataset? Thank you for your work hard.

**Comment by chufengt** [comment]
just calculating the number of positive samples and dividing the total samples.

**Comment by nanhui69** [comment]
> just calculating the number of positive samples and dividing the total samples.
in the code can ,where to modify it?

**Comment by chufengt** [comment]
> > just calculating the number of positive samples and dividing the total samples.
> > in the code can ,where to modify it?

Sorry, it's a pre-processing step and there is no code. It's really easy to implement it.
