### ISSUE TITLE
test on one image 

### ISSUE THREAD

**Issue by A7med01** [chufengt/iccv19_attribute#46]
First thanks for this great work,
how to test the model on only one image and get the predicted labels ?

**Comment by chufengt** [comment]
Sorry for the later reply.
See issue #27 for a quick response.
I will try to provide a detailed script after these busy days.

**Comment by A7med01** [comment]
it is okay i write a script thanks

**Comment by phuonganhdo1808** [comment]
> it is okay i write a script thanks

sorry but would you please to share with me your script? I really need it for testing. Thank you so much.

**Comment by memona008** [comment]
> > it is okay i write a script thanks
> 
> sorry but would you please to share with me your script? I really need it for testing. Thank you so much.

Do you still need the script
