### ISSUE TITLE
the params in main.py for save model 

### ISSUE THREAD

**Issue by nanhui69** [chufengt/iccv19_attribute#47]
# remember best Accu and save checkpoint
        is_best = accu > best_accu
        best_accu = max(accu, best_accu)

        if epoch in args.decay_epoch:

the is_best param is not use for save model anywhere , if i want to auto save model according the best metric ,how to define it??/

**Comment by chufengt** [comment]
`
if is_best:
    save_checkpoint(...)
`

**Comment by nanhui69** [comment]
> `if is_best: save_checkpoint(...)`

ok， got it , thx doctor

**Comment by nanhui69** [comment]
another question is that  does this model is perform better than  resnet50 model  such as this repo ??  furthermore ,what‘s mean for this li for idx in range(105):
        dataset['att_name'].append(data['peta'][0][0][1][idx, 0][0])  
 in the transform_peta.py，isn't attribute num 65 for peta data？？？

**Comment by chufengt** [comment]
What do you mean? There is no `transform_peta.py`.

**Comment by nanhui69** [comment]
> What do you mean? There is no `transform_peta.py`.

just refer this train code  :—> https://github.com/dangweili/pedestrian-attribute-recognition-pytorch  ,and   i find you make an ccommment under this repo. i cannot understand” for idx in range(105):
dataset['att_name'].append(data['peta'][0][0][1][idx, 0][0])　“ in transform_peta.py

**Comment by chufengt** [comment]
It seems PETA originally have 105 attributes, including many color attributes, but only 61 attributes are commonly used.
I didn't use this script. I downloaded the train/test list from https://github.com/asc-kit/vespa/tree/master/generated .
