### ISSUE TITLE
hi.. i want to train custom dataset(64 binary attribute)... is it possible without a pretrained model?

### ISSUE THREAD

**Issue by monorock** [chufengt/iccv19_attribute#48]

**Comment by chufengt** [comment]
sure, it's ok to train from scratch, just try to increase the training time

**Comment by Pyenb** [comment]
Hey there @monorock 

Sorry to contact you this way. My name is Ben, and I am a hobby developer. I am planning to start a new GitHub organization and, after much consideration, decided on the name "MonoRock." Unfortunately, I discovered that it is already taken.

I noticed that the account doesn’t seem to be in use, so I wanted to ask if there’s any chance you might consider transferring it to me? And if not, that is also no problem 👍

Best regards,
Ben
