### ISSUE TITLE
Clothes Color recognition 

### ISSUE THREAD

**Issue by abhigoku10** [chufengt/iccv19_attribute#50]
@chufengt  hi i had one query what was the intent of selecting "inception_3b_output_out,inception_4d_output_out,inception_5b_output_out" features  was there any logical reason behind it . I want to improve gender detection and what to recognize the color of the clothes for the custom datasets so how to do it besides adding more custom dataset?
Thanks in advance

**Comment by chufengt** [comment]
1. I choose these features just for convenience, you can replace them with other multi-scale features.
2. You mean recognizing the color of clothes? You can try to train a new model with the color attributes.

**Comment by abhigoku10** [comment]
@chufengt  thanks for the response 
1. which other multi-scale features can you suggest ?
2. yes clothes color , i tried to train a new model but the accuracy is less than 0.5 mAP , it is getting confused with the lower wear color and upperwear color  any other thoughts on that from architecture point of view

**Comment by chufengt** [comment]
1. for example, features of different residual blocks in ResNet.
2. actually the color attributes are usually hard to recognize, i have no idea too.

**Comment by abhigoku10** [comment]
thanks for the response , how will the architecture be if i change the backbone to ghostnet , resnext , since they are more efficient in image classification

**Comment by chufengt** [comment]
just replacing the BNInception with your custom backbones, and selecting the proper features to perform ALM

**Comment by abhigoku10** [comment]
Can we do multi-task learning with with the current architecture ?

**Comment by chufengt** [comment]
sure, you can add any custom loss function to perform your tasks
