### ISSUE TITLE
Accuracy drop on pole mounted view images 

### ISSUE THREAD

**Issue by abhigoku10** [chufengt/iccv19_attribute#51]
@chufengt  i tested the pre-trained model on eye-level captured videos/images and the results are acceptable but with little change, in the camera view ie pole-mounted view images the accuracy drops considerably through RAP dataset has surveillance images captured at the pole-mounted view, is re-training the only approach to get the best accuracy ??

**Comment by chufengt** [comment]
It seems the generalization between different scenarios is not good.
I think re-training on your custom dataset may work better.
