### ISSUE TITLE
Attention change 

### ISSUE THREAD

**Issue by abhigoku10** [chufengt/iccv19_attribute#52]
@chufengt  hi in your source code you have added attention module i have a query on this 

1. what is the reason of selection channel attention based attention 
2. which other attention module do u suggest instead of channel-based 
3. can we use multihead attention modules to improve the accuracy 
THnaks in adavance !!!

**Comment by chufengt** [comment]
1. similar motivation as SE-Net, and channel attention is somehow more efficient
2. you can try to replace it with other types of attention
3. sure, maybe multi-head attention gives better results

**Comment by abhigoku10** [comment]
What type of attentions should i replace with ? any suggestion

**Comment by chufengt** [comment]
e.g. spatial attention or combine channel and spatial attention, also multi-head attention

**Comment by abhigoku10** [comment]
@chufengt had one query if we have multi-head attention then can we not have STN, just want to knw how much dependency is there on STN module ??

**Comment by chufengt** [comment]
STN is a vital component of our method. 
You should treat your model equipped with multi-head attention as a new model and compared it with our ALM model, instead of treating it as an ALM variant.

**Comment by abhigoku10** [comment]
@chufengt  thanks for the response will do the same and share the results with you
