### ISSUE TITLE
Differentiate ROI pooling implementation

### ISSUE THREAD

**Issue by abhigoku10** [chufengt/iccv19_attribute#53]
@chufengt  can you share the source code for the architecture  having differentiate ROI pooling  or the differentiate ROI pooling module wanted to check the accuracy and conversion to onnx for PAR, thanks in advance

**Comment by chufengt** [comment]
Sorry, I just said we need an operation similar to a differentiable ROI pooling module, and we choose STN in the end.
We didn't implement any model with an explicit differentiable ROI pooling module.

**Comment by abhigoku10** [comment]
@chufengt oh wokay since STN we are not able to convert to tensorRT so thought we shall replace it with ROI pooling , is there any other modules which i can replace STN with ??

**Comment by chufengt** [comment]
maybe a box predictor + RoI pooling
the predictor used to predict the cropped region in STN
