### ISSUE TITLE
Number of attributes vs accuracy 

### ISSUE THREAD

**Issue by abhigoku10** [chufengt/iccv19_attribute#54]
@chufengt, since RAP dataset has 51 attributes and PA100k, has 26 attributes so we are getting mA=81.0 and 82.0 , if i train rap dataset or PA100k dataset with only 2-3 attributes ie Female,Age and Body time will my accuracy improve for all the three class ?? and will the model size decrease

**Comment by chufengt** [comment]
It's hard to say before experiments, other attributes may be helpful or harmful for the training of these three attributes.

**Comment by abhigoku10** [comment]
@chufengt  okay so selection of attribute is more important than having a number of attributes right !!

**Comment by chufengt** [comment]
i think so

**Comment by abhigoku10** [comment]
@chufengt  does the accuracy of the model depend on the mutual exclusiveness of the attributes ie if attribute is clearly distinguishable then will be getting better accuracy ??

**Comment by chufengt** [comment]
possible, actually it's a common problem in multi-task / multi-label learning.
here is an example:
Fully-Adaptive Feature Sharing in Multi-Task Networks with Applications in Person Attribute Classification, CVPR 2017.

**Comment by abhigoku10** [comment]
@chufengt  can share the bottlenecks or improvements which can be done for the current architecture which can boost the accuracy to mA=90-95 for the standard dataset.

**Comment by chufengt** [comment]
I didn't research on this area after this work, you can see some recent published works for a reference
