### ISSUE TITLE
Re-Training on public dataset 

### ISSUE THREAD

**Issue by abhigoku10** [chufengt/iccv19_attribute#55]
@chufengt I am re-training PAR on the PA100k dataset, but i am not getting the same results for 6th epoch as you have achieved ? for 6th epoch of re-training i am getting mA-0.78, 101th epoch mA=0.82 but original 6th epoch mA is 0.86 , only difference i am training from scratch with self.weights= None . Any thoughts y there is so much difference ?? and what was the reason of training all the datasets with small epochs ie <10?

**Comment by chufengt** [comment]
actually the final ALM was trained with a warm-up step: (see #25)
1. train a naive BNInception model (without the proposed ALM module) on the dataset
2. equipped with the ALM module (randomly initialized) and initialized the BNInception part with the previously trained parameters

**Comment by abhigoku10** [comment]
@chufengt  thanks for the response, i trained the model with enabling BN inception and i was able to get good boost in the accuracy , so ideally STN and BN inception module is playing a vital role in the accurracy aspect but how to improve the accuracy more than mA = 85 ?

**Comment by chufengt** [comment]
You said F1 score = 85 for PA-100K?
Have you tried the warm-up strategy mentioned above? There are no other tricks.
