### ISSUE TITLE
Paper understanding 

### ISSUE THREAD

**Issue by abhigoku10** [chufengt/iccv19_attribute#58]
@chufengt thanks for your work i was trying to understand the advantages of your work , i had a query when i read the paper and with the implementation give "The proposed framework does not require additional region annotations and can be trained end-to-end with multi-level deep supervision." so what does this above sentence signifies, since most of the other architecture take annotation with label encoding and train the module , cna you please clarify this part ?
Thanks in adavane

**Comment by chufengt** [comment]
it means we also trained the model with the same annotations, i.e. only yes/no for each attribute
additional region annotation means something like a bounding boxes, which is absent in those dataset
