### ISSUE TITLE
Single Stage network with PAR

### ISSUE THREAD

**Issue by abhigoku10** [chufengt/iccv19_attribute#59]
@chufengt  thanks for open sourcing the code I had a few queries 
1. can we integrate the current implementation by removing the backbone with any object detector(yolov5) module?
2. Can you clarify the purpose of channel attention and stn module is it to help is the localization of the attributes and make the model learn better ??
3. Just a thought if we have a just a backbone+Channel attention will we able to do multilabel classification with just the flow . THe intent is i am planning to add an addition head to the yolov4/5 from the feature backbone just use your channel attention module and loss for these and add the loss to the overall loss value

Thanks in advance

**Comment by chufengt** [comment]
1. I think it works.
2. STN was used to localize attributes, and channel attention was used to enhance the representation.
3. Of course you can do multi-label classification with such a model.

**Comment by abhigoku10** [comment]
@chufengt i tried to do it with retinanet but unfortunately, i am not able to get the flow, i mean can we add PAR besides the feature extraction and stn to the architecture even considering the loss, how will we make the model learn that it has to learn from the perspective bounding box ?? can you share your idea, any architecture should be fine for me

**Comment by chufengt** [comment]
@abhigoku10 sorry I have no idea about it, since it seems beyond the scope of this area
