### ISSUE TITLE
loss question

### ISSUE THREAD

**Issue by meixitu** [chufengt/iccv19_attribute#6]
Hi @chufengt ,
    Thanks for your great job and sharing.
     I just have a question about the loss
in your paper:
![image](https://user-images.githubusercontent.com/32910309/78414855-14754380-75d3-11ea-9c9a-9ad664e21bfd.png)
it is weight for each attribute

In your code:
![image](https://user-images.githubusercontent.com/32910309/78414869-29ea6d80-75d3-11ea-85a6-bb390d71aec6.png)
it is weight when calculate positive label loss

I think they are not equivalent.

Is there some mistake?

Thanks
Meixitu

**Comment by chufengt** [comment]
Yes, I think there is a mismatch.
In the paper, I give the standard style (Li et al. 2015), which weights for both positive and negative.
In the code, I think I have tried both of these styles and find the results are similar.

**Comment by meixitu** [comment]
@chufengt ，

    Thank you.

Meixitu
