### ISSUE TITLE
Localization of STN models 

### ISSUE THREAD

**Issue by abhigoku10** [chufengt/iccv19_attribute#63]
@chufengt hi thanks for sharing the code base, for localization of attributes which intermediate feature[feat3b,feat4d,feat5b] gives the best accuracy ?
Q2. Does the accuracy of localization varry based on the feature layer and the attributes eg: global attributes localization is obtained best from feat5d and local attributes localization is best from feat3b like that 

Pls share your thoughts

**Comment by chufengt** [comment]
1. I didn't try these 3 feature layers individually.
2. It makes sense since global attributes usually require high-level semantics (e.g. feat5d) and local attributes benefit from higher resolution (e.g. feat3b).

**Comment by abhigoku10** [comment]
@chufengt  any thoughts on how to calculate the accuracy of the localization from different feature layers

**Comment by chufengt** [comment]
Just try to attach the ALM module on a specific feature layer (e.g. feat3b only), and train these different models.
Using only one feature layer is usually worse than multi-layers.
