### ISSUE TITLE
Attribute accuracy 

### ISSUE THREAD

**Issue by abhigoku10** [chufengt/iccv19_attribute#64]
@chufengt  hi i had few queries to increase the accuracy of the model 
1. If i reduce the number of attributes to only 6 ie global attributes can we see increased accuracy for the RAP / PA100k models 
2. can increase the dataset by merging two data and train the model will be increase attribute accuracy 
Can you share your thoughts on how to improve the accurracy

**Comment by chufengt** [comment]
1. it depends on the actual experiments.
2. the main obstacle might be how to unify the attributes in two different datasets.
