### ISSUE TITLE
Pre-trained model cannot be decompressed!

### ISSUE THREAD

**Issue by zhuangqirong** [chufengt/iccv19_attribute#69]
The pre-training model downloaded from Google disk cannot be unzipped..

**Comment by chufengt** [comment]
Do not attempt to unzip it, just load it directly: torch.load('xxx.pth.tar')

**Comment by zhuangqirong** [comment]
> Do not attempt to unzip it, just load it directly: torch.load('xxx.pth.tar')

Thank you very much for your reply and have a nice day！
