### ISSUE TITLE
Color recognition enquiry

### ISSUE THREAD

**Issue by lokeycookie** [chufengt/iccv19_attribute#73]
Hello! I want to ask a question.

Is there a reason why the model is not trained for color recognition when the dataset contained annotations for color?

**Comment by chufengt** [comment]
Please check the original papers for the reason that choosing these attributes for experiments.

For example, in RAP ([A Richly Annotated Dataset for Pedestrian Attribute Recognition](http://arxiv.org/abs/1603.07054)):
> Due to the highly unbalanced distribution of attributes, totally 51 binary attributes are selected in our experiments. The attribute is selected when the positive examples’ ratio in the dataset is higher than 0.01.
